# Generated by Django 5.0.2 on 2024-02-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menmbers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='thumbnails'),
        ),
    ]
