# Generated by Django 5.0.2 on 2024-02-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menmbers_app', '0003_category_tag_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='menmbers_app.tag'),
        ),
    ]
